# Workflow for S3 Parquet File Processing
name: S3 Parquet File Processing

on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  process-s3-parquet:
    name: Process S3 Parquet Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Process S3 Parquet Files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python s3_parquet_handler.py